name: LukynkaCore
version: '${project.version}'
main: cz.lukynka.core.Main
api-version: 1.18
authors: [ LukynkaCZE ]
commands:
  gms:
    description: a
  gmc:
    description: b
  gma:
    description: c
  gmsp:
    description: d
